substitutions:
  device_id: my-mr24hpc1-sensor
  device_name: My MR24HPC1 Sensor
  uart_rx_pin: "9"
  uart_tx_pin: "8"
  
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "{{YOUR ENCRYPTION KEY}}"

ota:
  password: "{{YOUR OTA PASSWORD}}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_id}
    password: "{{PASSWORD}}"
    
packages:
  device_base: !include external_components/mr24/packages/mr24hpc1.yaml
